### ISSUE TITLE
novnc安装在windows7 X86系统上的访问问题！

### ISSUE THREAD

**Issue by BeiJing-LiChenXing** [novnc/websockify-js#20]
所有的服务都部署好了，但是在浏览器访问时，会报1005的错！
```
WebSocket connection
Version undefined ,subprotocol :
connected to target
target connection error
WebSocket client disconnected :1005 [ ]
```
我将centos系统上生成的安全链接证书拷贝到了windows上 (self.pem)，还是同样的问题。不知道是哪些故障导致的，网上很难找到相关的故障信息。请求帮助.

**Comment by BeiJing-LiChenXing** [comment]
![image](https://user-images.githubusercontent.com/49607140/71453856-90881000-27c8-11ea-8dfa-824aa46c44d6.png)

**Comment by BeiJing-LiChenXing** [comment]
![image](https://user-images.githubusercontent.com/49607140/71454650-b8797280-27cc-11ea-941f-2a421b1564b6.png)

**Comment by CendioOssman** [comment]
I'm afraid we can only provide support in English. Please see if there is some Chinese forum that can help you out.

**Comment by 1771979508** [comment]
Host OS: Windows 10
VNC Server on Host: UltraVNC 1.3.2
Client OS: Windows 10
Client Browser: chrome latest
Proxy: websockify-js

when I try to connect, It report connect failed.

WebSocket connection
Version undefined ,subprotocol :
connected to target
target connection error
WebSocket client disconnected :1005 [ ]
