### ISSUE TITLE
how to encrypted WebSocket connections (wss://) on win server?

### ISSUE THREAD

**Issue by vwater** [novnc/websockify-js#21]
i use tightvnc +websockify+novnc, and i want to novnc provide the https connection. i have right installed the novnc and tightvnc and websockify ,then i create the selp.pem in the noVNC/utils folder。however when i browse the site with "https://ip:6080/vnc.html", the browser tells me the site can't provide any info.
![image](https://user-images.githubusercontent.com/41112571/75348042-0ac63500-58dd-11ea-8220-94524dc12562.png)

**Comment by vwater** [comment]
it works well with '--cert=CERT' directly following the command, like the pattern： 
 /websockify.js [options] SOURCE_ADDR:PORT TARGET_ADDR:PORT --cert=CERT
thank you！

**Comment by CendioOssman** [comment]
Glad you got it sorted out. :)
